<?php
/**
 * AGENT-TEST-CORE harness — deploy as ONE permanently-active Code Snippets snippet.
 *
 * This is shared infrastructure for every per-skill test suite in this repo. Deploy
 * this snippet once (name it exactly "AGENT-TEST-CORE harness (keep active, do not
 * delete)"), leave it active permanently, then deploy one additional snippet per
 * skill containing that skill's suite code (see docs/test-harness-guide.md and
 * .claude/skills/<skill>/tests.php).
 *
 * Do not edit this file without also updating the deployed snippet's `code` field to
 * match — this repo file is the source of truth; the snippet is a mirror of it.
 */

if ( ! function_exists( 'agent_test_assert' ) ) {
	/**
	 * Record one assertion result. Call this from inside a suite's
	 * `agent-test/run-suite/{suite}` action handler.
	 *
	 * @param string $suite    Suite slug, matches the skill folder name, e.g. 'jetengine-query-builder'.
	 * @param string $id       Short stable test id within the suite, e.g. 'qb-1'.
	 * @param string $claim    One-line paraphrase of the SKILL.md claim being tested, ideally with a section/anchor.
	 * @param bool   $pass     Whether the assertion passed. Compute this yourself in the test body —
	 *                         the harness does not attempt generic value comparison.
	 * @param mixed  $expected What SKILL.md claims should happen. Keep it JSON-serializable.
	 * @param mixed  $actual   What was actually observed. Keep it JSON-serializable.
	 * @param string $notes    File:line citation for the claim, plus anything a future agent needs
	 *                         to judge "is the CODE wrong, or is this TEST wrong" on a FAIL.
	 */
	function agent_test_assert( $suite, $id, $claim, $pass, $expected, $actual, $notes = '' ) {
		if ( ! isset( $GLOBALS['agent_test_current_results'] ) ) {
			$GLOBALS['agent_test_current_results'] = array();
		}
		$GLOBALS['agent_test_current_results'][] = array(
			'id'       => $id,
			'claim'    => $claim,
			'pass'     => (bool) $pass,
			'expected' => $expected,
			'actual'   => $actual,
			'notes'    => $notes,
		);
	}
}

if ( ! function_exists( 'agent_test_run_suite' ) ) {
	/**
	 * Fire a suite's registered action and collect everything it asserted.
	 *
	 * A `fatal_error` in the return value (not a failed assertion) means the SUITE
	 * ITSELF broke — a missing fixture, a renamed class, a typo in the test code — not
	 * that the underlying plugin behavior is wrong. Always check `fatal_error` first
	 * before reading individual `results` entries.
	 */
	function agent_test_run_suite( $suite ) {
		$GLOBALS['agent_test_current_results'] = array();
		$error = null;
		try {
			do_action( "agent-test/run-suite/{$suite}" );
		} catch ( \Throwable $e ) {
			$error = array(
				'exception' => get_class( $e ),
				'message'   => $e->getMessage(),
				'at'        => $e->getFile() . ':' . $e->getLine(),
			);
		}
		$results = $GLOBALS['agent_test_current_results'];
		$total   = count( $results );
		$passed  = count( array_filter( $results, function( $r ) { return $r['pass']; } ) );
		return array(
			'suite'       => $suite,
			'run_at'      => current_time( 'mysql' ),
			'fatal_error' => $error,
			'summary'     => array( 'total' => $total, 'passed' => $passed, 'failed' => $total - $passed ),
			'results'     => $results,
		);
	}
}

add_action( 'rest_api_init', function() {

	// GET /agent-test/v1/suite/{suite} — runs the named suite fresh and returns JSON.
	register_rest_route( 'agent-test/v1', '/suite/(?P<suite>[a-z0-9_-]+)', array(
		'methods'  => 'GET',
		'callback' => function( $req ) {
			$suite = $req->get_param( 'suite' );
			if ( ! has_action( "agent-test/run-suite/{$suite}" ) ) {
				return new WP_Error(
					'unknown_suite',
					"No suite registered for '{$suite}' — is that suite's snippet active?",
					array( 'status' => 404 )
				);
			}
			return agent_test_run_suite( $suite );
		},
		'permission_callback' => function() { return current_user_can( 'manage_options' ); },
	) );

	// GET /agent-test/v1/suites — lists every currently-registered (active) suite.
	register_rest_route( 'agent-test/v1', '/suites', array(
		'methods'  => 'GET',
		'callback' => function() {
			global $wp_filter;
			$suites = array();
			foreach ( $wp_filter as $tag => $hook ) {
				if ( strpos( $tag, 'agent-test/run-suite/' ) === 0 ) {
					$suites[] = substr( $tag, strlen( 'agent-test/run-suite/' ) );
				}
			}
			return $suites;
		},
		'permission_callback' => function() { return current_user_can( 'manage_options' ); },
	) );
} );
